version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"  # example port for browser/test access

  user-service:
    build: ./user-service
    ports:
      - "8002:8000"

  chat-service:
    build: ./chat-service
    ports:
      - "8003:8000"

  message-history-service:
    build: ./message-history-service
    ports:
      - "8004:8000"

  group-service:
    build: ./group-service
    ports:
      - "8005:8000"

  notification-service:
    build: ./notification-service
    ports:
      - "8006:8000"

  media-service:
    build: ./media-service
    ports:
      - "8007:8007"   # Gunicorn listens on 8007

  analytics-service:
    build: ./analytics-service
    ports:
      - "8008:8000"

  gateway:
    build: ./gateway
    ports:
      - "8090:80"  # changed to avoid conflict
    depends_on:
      - frontend
      - auth-service
      - user-service
      - chat-service
      - message-history-service
      - group-service
      - notification-service
      - media-service
      - analytics-service
