version: '3.8'

services:
  frontend:
    build: ./frontend
    expose:
      - "3000"

  auth-service:
    build: ./auth-service
    expose:
      - "8000"

  user-service:
    build: ./user-service
    expose:
      - "8000"

  chat-service:
    build: ./chat-service
    expose:
      - "8000"

  message-history-service:
    build: ./message-history-service
    expose:
      - "8000"

  group-service:
    build: ./group-service
    expose:
      - "8000"

  notification-service:
    build: ./notification-service
    expose:
      - "8000"

  media-service:
    build: ./media-service
    expose:
      - "8007"

  analytics-service:
    build: ./analytics-service
    expose:
      - "8000"

  gateway:
    build:
     context: .
     dockerfile: gateway/Dockerfile
    ports:
    - "8090:80"
    depends_on:
    - frontend
    - auth-service
    - user-service
    - chat-service
    - message-history-service
    - group-service
    - notification-service
    - media-service
    - analytics-service

